[general]
import = ["~/.config/alacritty/nord-darker.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 12
y = 12
